<?xml version="1.0"?>

<robot name="scout_v2" 
    xmlns:xacro="http://ros.org/wiki/xacro">

    <xacro:arg name="robot_namespace" default="/" /> 

    <xacro:include filename="$(find scout_description)/urdf/scout_wheel_type1.xacro" />
    <xacro:include filename="$(find scout_description)/urdf/scout_wheel_type2.xacro" />

    <!-- Variables -->
    <xacro:property name="M_PI" value="3.14159"/>
    <xacro:property name="baseline" value="0.075" />

    <!-- Vehicle Geometries -->
    <xacro:property name="base_x_size" value="0.9250000" />
    <xacro:property name="base_y_size" value="0.380000" />
    <xacro:property name="base_z_size" value="0.210000" />

    <xacro:property name="wheelbase" value="0.498" />
    <xacro:property name="track" value="0.58306" />
    <xacro:property name="wheel_vertical_offset" value="-0.0702" />

    <xacro:property name="wheel_length" value="1.1653e-01" />
    <xacro:property name="wheel_radius" value="1.6459e-01" />

    <!-- Base link -->
    <link name="base_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <mesh filename="package://scout_description/meshes/scout_v2/base_link.dae" />
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0.008" rpy="0 0 0" />
            <geometry>
                <box size="${base_x_size} ${base_y_size} ${base_z_size}"/>
            </geometry>
        </collision>
        <collision>
            <origin xyz="0 0 ${base_z_size/6}" rpy="0 0 0" />
            <geometry>
                <box size="${base_x_size/6} ${base_y_size*1.65} ${base_z_size/3}"/>
            </geometry>
        </collision>
    </link>

    <link name="base_footprint"/>

    <joint name="base_footprint_joint" type="fixed">
        <origin xyz="0 0 ${wheel_vertical_offset - wheel_radius}" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="base_footprint" />
    </joint>

    <link name="inertial_link">
        <inertial>
            <mass value="40" />
            <origin xyz="0.0 0.0 0.0" />
            <inertia ixx="2.288641" ixy="0" ixz="0" iyy="5.103976" iyz="0" izz="3.431465" />
        </inertial>
    </link>

    <joint name="inertial_joint" type="fixed">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="inertial_link" />
    </joint>

    <!-- Scout wheel macros -->
    <!-- wheel labeled from 0 to 3, conter-clockwise, starting from front right wheel -->
    <!-- motor 1 and 2 (left side) are mechanically installed in a reversed direction -->
    <xacro:scout_wheel_type1 wheel_prefix="front_right">
        <origin xyz="${wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="3.14 0 0" />
    </xacro:scout_wheel_type1>
    <xacro:scout_wheel_type2 wheel_prefix="front_left">
        <origin xyz="${wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
    </xacro:scout_wheel_type2>
    <xacro:scout_wheel_type1 wheel_prefix="rear_left">
        <origin xyz="${-wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
    </xacro:scout_wheel_type1>
    <xacro:scout_wheel_type2 wheel_prefix="rear_right">
        <origin xyz="${-wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="3.14 0 0" />
    </xacro:scout_wheel_type2>


    <!-- base_link of the sensor-->
    <link name="oak-d_frame"/>

    <joint name="oak_center_joint" type="fixed">
        <parent link="base_link"/>
        <child link="oak-d_frame"/>
        <origin xyz="0.4 0.0 0.25" rpy="0 0 0" />
    </joint>

<!-- device Center -->
    <link name="oak_model_origin">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://depthai_bridge/urdf/models/OAK-D-PRO.stl" />
                <material name="mat">
                <color rgba="0.8 0.8 0.8 0.8"/> 
                <!-- TODO: FIX COLORING -->
            </material>
            </geometry>
        </visual>
    </link>

    <joint name="oak_model_origin_joint" type="fixed">
        <parent link="oak-d_frame"/>
        <child link="oak_model_origin"/>
        <origin xyz="0 0 0" rpy="1.5708 0 1.5708" />
    </joint>

    <!-- IMU -->
        <link name="oak_imu_frame" />
        <joint name="oak_imu_joint" type="fixed">
            <parent link="oak-d_frame"/>
            <child link="oak_imu_frame"/>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </joint>

<!-- RGB Camera -->
    <link name="oak_rgb_camera_frame" />
    
    <joint name="oak_rgb_camera_joint" type="fixed">
        <parent link="oak-d_frame"/>
        <child link="oak_rgb_camera_frame"/>
        <origin xyz="0 0 0" rpy="0 0 0" />
    </joint>

    <link name="oak_rgb_camera_optical_frame"/>
    
    <joint name="oak_rgb_camera_optical_joint" type="fixed">
        <origin xyz="0 0 0" rpy="-${M_PI/2} 0.0 -${M_PI/2}"/>
        <parent link="oak_rgb_camera_frame"/>
        <child link="oak_rgb_camera_optical_frame"/>
    </joint>

<!-- Left Camera -->
    <link name="oak_left_camera_frame" />
    
    <joint name="oak_left_camera_joint" type="fixed">
        <parent link="oak-d_frame"/>
        <child link="oak_left_camera_frame"/>
        <origin xyz="0 ${baseline/2} 0" rpy="0 0 0" />
    </joint>

    <link name="oak_left_camera_optical_frame"/>
    
    <joint name="oak_left_camera_optical_joint" type="fixed">
        <origin xyz="0 0 0" rpy="-${M_PI/2} 0.0 -${M_PI/2}"/>
        <parent link="oak_left_camera_frame"/>
        <child link="oak_left_camera_optical_frame"/>
    </joint>

    
<!-- right Camera -->
    <link name="oak_right_camera_frame" />
    
    <joint name="oak_right_camera_joint" type="fixed">
        <parent link="oak-d_frame"/>
        <child link="oak_right_camera_frame"/>
        <origin xyz="0 -${baseline/2} 0" rpy="0 0 0" />
    </joint>

    <link name="oak_right_camera_optical_frame"/>
    
    <joint name="oak_right_camera_optical_joint" type="fixed">
        <origin xyz="0 0 0" rpy="-${M_PI/2} 0.0 -${M_PI/2}"/>
        <parent link="oak_right_camera_frame"/>
        <child link="oak_right_camera_optical_frame"/>
    </joint>
    

</robot>
